##  Plugin Information  ##
name: MotdManager
version: version-number-unknown
main: syam.motdmanager.MotdManager
description: Changes server MOTD!
website: http://sakura-server.net/
##  Original Author     ##
author: syam
commands:
    motdmanager:
      usage: /motdmanager - to see the help
      aliases: [motd, mm]
      description: To see the MotdManager help.
permissions:
    motdmanager.add:
        default: op
        description: Allow use add command
    motdmanager.remove:
        default: op
        description: Allow use remove command
    motdmanager.list:
        default: op
        description: Allow use list command
    motdmanager.maxplayer:
        default: op
        description: Allow use maxplayer command
    motdmanager.reload:
        default: op
        description: Allow use reload command